---
- name: Copy Dockerfiles for client 
  copy:
      src: /home/ry/Desktop/dev/yolo_ansible/yolo/client/Dockerfile
      dest: /var/www/yolo-app/
  with_items:
    - Dockerfile

- name: Build the front-end Docker container
  command: docker build -t yolo-frontend-app /home/ry/Desktop/dev/yolo_ansible/yolo/client -f /home/ry/Desktop/dev/yolo_ansible/yolo/client/Dockerfile

- name: Start the front-end container using Docker Compose
  command: docker-compose -f /var/docker-compose/docker-compose.yml up -d frontend