---
- name: Deploy Yolo Application
  hosts: default
  become: yes
  tasks:
    - name: Setup task
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python3-pip
          - python3-setuptools
          - python3-dev
          - docker.io
          - docker-compose
          - git

    - name: Clone application code from GitHub 
      git:
        repo: https://github.com/WanguiR/yolo_ansible.git
        dest: /var/www/yolo-app
        update: yes
      register: git_clone
      
    - name: Copy dockercompose 
      copy:
        src:  /home/ry/Desktop/dev/yolo_ansible/yolo/docker-compose.yml 
        dest: /var/docker-compose    
      when: git_clone.changed

    - name: Set up Front-end
      role:
        name: client

    - name: Set up Back-end
      role:
        name: backend



